/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shubhanshu Soni (https://sketchfab.com/sonishubhanshu99)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-37249acae18b406d8c1c160d7c0bc8e6
title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Earth({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/earth.gltf");
  // const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group rotation={[-Math.PI / 2, 0, -1.54]} scale={.41}>
                  <mesh
                    geometry={nodes.Earth_Earth_0.geometry}
                    material={materials.Earth}
                    position={[6,6,1]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/earth.gltf");
